Repository dnd-side-project/dnd-5th-10-backend, pull requests merged in 2021-08, with the labels that each got.

#27 fix: JwtProperties에 노출되어있던 secret을 config파일에서 가져오도록 분리함
  src/main/java/com/dnd10/iterview/config/SecurityConfig.java
  src/main/java/com/dnd10/iterview/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/dnd10/iterview/config/jwt/JwtProperties.java
  src/main/java/com/dnd10/iterview/config/oauth2/CustomOAuth2SuccessHandler.java
Labels: bug

#25 Question Domain 확인된 api 개발 완료
  pom.xml
  src/main/java/com/dnd10/iterview/config/SwaggerConfig.java
  src/main/java/com/dnd10/iterview/controller/QuestionController.java
  src/main/java/com/dnd10/iterview/dto/QuestionRequestDto.java
  src/main/java/com/dnd10/iterview/dto/QuestionResponseDto.java
  src/main/java/com/dnd10/iterview/entity/Question.java
  src/main/java/com/dnd10/iterview/repository/QuestionRepository.java
  src/main/java/com/dnd10/iterview/repository/QuestionSearchExtension.java
  src/main/java/com/dnd10/iterview/repository/QuestionSearchExtensionImpl.java
  src/main/java/com/dnd10/iterview/resource/QuestionResource.java
  src/main/java/com/dnd10/iterview/service/QuestionService.java
  src/main/java/com/dnd10/iterview/service/QuestionServiceImpl.java
Labels: enhancement

#30 Hotfix tag
  src/main/java/com/dnd10/iterview/controller/QuestionController.java
  src/main/java/com/dnd10/iterview/service/QuestionService.java
  src/main/java/com/dnd10/iterview/service/QuestionServiceImpl.java
Labels: bug

#20 Feature/14 answer
  pom.xml
  src/main/java/com/dnd10/iterview/IterviewApplication.java
  src/main/java/com/dnd10/iterview/advice/ExceptionAdvice.java
  src/main/java/com/dnd10/iterview/config/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/dnd10/iterview/controller/AnswerController.java
  src/main/java/com/dnd10/iterview/controller/LikeAnswerController.java
  src/main/java/com/dnd10/iterview/controller/UserController.java
  src/main/java/com/dnd10/iterview/dto/AnswerDto.java
  src/main/java/com/dnd10/iterview/dto/LikeAnswerDto.java
  src/main/java/com/dnd10/iterview/entity/Answer.java
  src/main/java/com/dnd10/iterview/entity/BaseTimeEntity.java
  src/main/java/com/dnd10/iterview/entity/LikeAnswer.java
  src/main/java/com/dnd10/iterview/entity/Question.java
  src/main/java/com/dnd10/iterview/repository/AnswerRepository.java
  src/main/java/com/dnd10/iterview/repository/LikeAnswerRepository.java
  src/main/java/com/dnd10/iterview/service/AnswerService.java
  src/main/java/com/dnd10/iterview/service/AnswerServiceImpl.java
  src/main/java/com/dnd10/iterview/service/LikeAnswerService.java
  src/main/java/com/dnd10/iterview/service/LikeAnswerServiceImpl.java
  src/main/java/com/dnd10/iterview/util/Order.java
  src/test/java/com/dnd10/iterview/service/AnswerServiceTest.java
Labels: enhancement

#41 feat: User 도메인에 프로필 이미지 Url 컬럼을 추가함
  src/main/java/com/dnd10/iterview/config/oauth2/CustomOAuth2UserService.java
  src/main/java/com/dnd10/iterview/dto/UserDto.java
  src/main/java/com/dnd10/iterview/entity/User.java
Labels: enhancement

#44 feat: 내가 한 답변 조회에 QuestionResponseDto를 추가로 실어서 보냄
  src/main/java/com/dnd10/iterview/controller/AnswerController.java
  src/main/java/com/dnd10/iterview/dto/MyAnswerDto.java
  src/main/java/com/dnd10/iterview/service/AnswerService.java
  src/main/java/com/dnd10/iterview/service/AnswerServiceImpl.java
Labels: enhancement

#45 Feature/my answer : 답변 API 관련 요구사항 반영
  src/main/java/com/dnd10/iterview/dto/AnswerResponseDto.java
  src/main/java/com/dnd10/iterview/service/AnswerServiceImpl.java
Labels: enhancement

#48 Question, Bookmark test 작성
  src/test/java/com/dnd10/iterview/service/BookmarkServiceTest.java
  src/test/java/com/dnd10/iterview/service/QuestionServiceTest.java
Labels: test

#50 fix: github 로그인 시 jwt 토큰 발행 못하는 에러 임시 수정
  src/main/java/com/dnd10/iterview/config/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/dnd10/iterview/config/oauth2/GithubOAuth2Info.java
Labels: bug
